### PR TITLE
refactor(web): extract input page utilities

### PR DESCRIPTION
**Pull request by beejjacobs**
## Describe your changes

Reduce duplicate code by adding utility functions for certain page types.

## Issue ticket number and link

Tickets:
https://pins-ds.atlassian.net/browse/A2-1097
https://pins-ds.atlassian.net/browse/A2-1098

## Type of change 🧩

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update
- [ ] Other (please explain in the description section above)

## Checklist before requesting a review

- [ ] I have performed a self-review of my own code
- [ ] I have double checked this work does not include any hardcoded secrets or passwords
- [ ] I have made corresponding changes to the documentation
- [ ] I have provided details on how I have tested my code
- [ ] I have referenced the ticket number above
- [ ] I have provided a description of the ticket
- [ ] I have included unit tests to cover any testable code changes

### CODE REVIEW

**Comment by beejjacobs** [comment]
Tests failing because of snapshots, related to fieldset. I think this was due to an error in the existing code which had `fieldSet` not `fieldset`.

**Review by james-hill-kc — APPROVED** [review]
Looks great to me! This should make building pages much easier :)

**Comment by beejjacobs** [comment]
Snapshots updated.

**Review by fabfab-kc — COMMENTED** [review]
Super!

**Review by james-hill-kc — APPROVED** [review]

**Review by fabfab-kc — DISMISSED** [review]
LGTM!

**Review by fabfab-kc — APPROVED** [review]
LGTM!

**Pull request merged**
